/**
 * The sample draft, kept in step with
 * `codes/backpy/tests/fixtures/sample_draft_id.txt`.
 *
 * It is deliberately flawed: causal language on a correlational design, a leap
 * from one faculty to a national claim, a consensus asserted without a single
 * citation, and self-reported measures never acknowledged as a limitation. One
 * example of each category the Draft Analyzer looks for, so a demo shows all
 * four without needing four drafts.
 */

export const SAMPLE_DRAFT_ID = "BAB I PENDAHULUAN\n\nPerkembangan media sosial dalam satu dekade terakhir telah mengubah cara mahasiswa mengelola waktu belajar. Banyak dosen melaporkan menurunnya konsentrasi mahasiswa di kelas. Media sosial jelas merupakan penyebab utama menurunnya kualitas pendidikan tinggi di Indonesia saat ini.\n\nRumusan masalah penelitian ini adalah: bagaimana hubungan antara intensitas penggunaan media sosial dengan prestasi akademik mahasiswa Fakultas Ekonomi Universitas Nusantara?\n\nBAB III METODOLOGI PENELITIAN\n\nPenelitian ini menggunakan pendekatan kuantitatif dengan desain survei potong lintang. Data dikumpulkan satu kali pada bulan Maret 2026 melalui kuesioner daring yang disebarkan kepada mahasiswa aktif Fakultas Ekonomi Universitas Nusantara. Sampel berjumlah 120 responden yang dipilih menggunakan teknik accidental sampling. Intensitas penggunaan media sosial diukur melalui laporan mandiri responden mengenai rata-rata durasi penggunaan harian. Prestasi akademik diukur menggunakan Indeks Prestasi Kumulatif yang dilaporkan sendiri oleh responden. Analisis data dilakukan dengan uji korelasi Pearson dan regresi linier sederhana.\n\nBAB IV HASIL DAN PEMBAHASAN\n\nHasil uji korelasi menunjukkan hubungan negatif yang signifikan antara durasi penggunaan media sosial dengan Indeks Prestasi Kumulatif (r = -0,42; p < 0,05). Temuan ini membuktikan bahwa penggunaan media sosial menurunkan prestasi akademik mahasiswa. Semakin lama seorang mahasiswa menggunakan media sosial, semakin rendah prestasi akademik yang akan dicapainya.\n\nDengan demikian dapat disimpulkan bahwa media sosial berdampak negatif terhadap prestasi akademik seluruh mahasiswa di Indonesia. Hasil ini sejalan dengan konsensus para ahli pendidikan di seluruh dunia yang telah lama menyatakan hal serupa.\n\nTemuan ini juga menunjukkan bahwa pembatasan akses media sosial di lingkungan kampus merupakan kebijakan yang efektif untuk meningkatkan mutu lulusan perguruan tinggi.\n\nBAB V PENUTUP\n\nPenelitian ini memiliki keterbatasan pada jumlah sampel yang relatif kecil sehingga hasilnya perlu diinterpretasikan dengan hati-hati. Penelitian selanjutnya disarankan menggunakan sampel yang lebih besar.\n";
