/**
 * Sample drafts, kept in step with `codes/backpy/tests/fixtures/`.
 *
 * Both are deliberately flawed, and flawed in the same four ways: causal
 * language on a design that cannot carry it, a leap from one narrow sample to a
 * sweeping population, a claim asserted without a citation, and a measurement
 * weakness never acknowledged. One example of each category the Draft Analyzer
 * looks for, so a demo shows all four without needing four drafts.
 *
 * Two languages because the agents follow the language of the manuscript. The
 * English one is what an English speaking reviewer should reach for first.
 */

export const SAMPLE_DRAFT_EN = "CHAPTER I INTRODUCTION\n\nRemote work has reshaped how knowledge workers experience their jobs. Since 2020,\norganisations worldwide have adopted hybrid arrangements at unprecedented scale.\nRemote work is clearly the decisive factor behind the decline in workplace\ncollaboration reported across the technology sector.\n\nThe research question guiding this study is: how do software engineers at a single\nmid-sized technology company describe their experience of collaboration under a\nhybrid work arrangement?\n\nCHAPTER III METHODOLOGY\n\nThis study adopts a qualitative interpretive design. Data were gathered through\nsemi-structured interviews with fourteen software engineers at one technology\ncompany in Jakarta, recruited through an internal announcement inviting volunteers.\nInterviews lasted between forty and sixty minutes and were conducted over video\ncall. Transcripts were analysed using thematic analysis following an inductive\ncoding process carried out by the researcher alone.\n\nCHAPTER IV FINDINGS AND DISCUSSION\n\nThree themes emerged from the analysis: fragmented awareness of colleagues' work,\na decline in spontaneous problem solving, and increased reliance on scheduled\nmeetings. Participants consistently described difficulty knowing what their\nteammates were working on.\n\nThese findings demonstrate that hybrid work arrangements cause a measurable\ndecline in collaboration quality among software engineers. The evidence therefore\nestablishes that organisations adopting hybrid models will experience reduced\ninnovation output over time.\n\nBecause all fourteen participants reported similar experiences, the findings can\nbe generalised to knowledge workers in hybrid arrangements more broadly.\n\nCHAPTER V CONCLUSION\n\nThis study concludes that hybrid work reduces collaboration. Organisations should\ntherefore require a minimum of four days of office attendance per week to protect\ncollaborative capacity.\n";

export const SAMPLE_DRAFT_ID = "BAB I PENDAHULUAN\n\nPerkembangan media sosial dalam satu dekade terakhir telah mengubah cara mahasiswa mengelola waktu belajar. Banyak dosen melaporkan menurunnya konsentrasi mahasiswa di kelas. Media sosial jelas merupakan penyebab utama menurunnya kualitas pendidikan tinggi di Indonesia saat ini.\n\nRumusan masalah penelitian ini adalah: bagaimana hubungan antara intensitas penggunaan media sosial dengan prestasi akademik mahasiswa Fakultas Ekonomi Universitas Nusantara?\n\nBAB III METODOLOGI PENELITIAN\n\nPenelitian ini menggunakan pendekatan kuantitatif dengan desain survei potong lintang. Data dikumpulkan satu kali pada bulan Maret 2026 melalui kuesioner daring yang disebarkan kepada mahasiswa aktif Fakultas Ekonomi Universitas Nusantara. Sampel berjumlah 120 responden yang dipilih menggunakan teknik accidental sampling. Intensitas penggunaan media sosial diukur melalui laporan mandiri responden mengenai rata-rata durasi penggunaan harian. Prestasi akademik diukur menggunakan Indeks Prestasi Kumulatif yang dilaporkan sendiri oleh responden. Analisis data dilakukan dengan uji korelasi Pearson dan regresi linier sederhana.\n\nBAB IV HASIL DAN PEMBAHASAN\n\nHasil uji korelasi menunjukkan hubungan negatif yang signifikan antara durasi penggunaan media sosial dengan Indeks Prestasi Kumulatif (r = -0,42; p < 0,05). Temuan ini membuktikan bahwa penggunaan media sosial menurunkan prestasi akademik mahasiswa. Semakin lama seorang mahasiswa menggunakan media sosial, semakin rendah prestasi akademik yang akan dicapainya.\n\nDengan demikian dapat disimpulkan bahwa media sosial berdampak negatif terhadap prestasi akademik seluruh mahasiswa di Indonesia. Hasil ini sejalan dengan konsensus para ahli pendidikan di seluruh dunia yang telah lama menyatakan hal serupa.\n\nTemuan ini juga menunjukkan bahwa pembatasan akses media sosial di lingkungan kampus merupakan kebijakan yang efektif untuk meningkatkan mutu lulusan perguruan tinggi.\n\nBAB V PENUTUP\n\nPenelitian ini memiliki keterbatasan pada jumlah sampel yang relatif kecil sehingga hasilnya perlu diinterpretasikan dengan hati-hati. Penelitian selanjutnya disarankan menggunakan sampel yang lebih besar.\n";
